baseUrl: https://leon.re
title: Knockin' on Heaven's Door
metaDataFormat: yaml
googleAnalytics: UA-48413769-8
enableRobotsTxt: true
enableEmoji: true

params:
  author: Yohann Leon
  description: A blog by Yohann, because heâ€™s got too much time on his hand
  email: sybiload@gmail.com

  social:
    github: https://github.com/obynio
    linkedin: https://www.linkedin.com/in/yohannleon
    instagram: https://www.instagram.com/yohann
    twitter: https://www.twitter.com/obynio
